const CONFIG = import.meta.env

export const CONTRACT_ADDRESS = CONFIG.VITE_CONTRACT_ADDRESS
export const CHAIN_ID = CONFIG.VITE_CHAIN_ID
export const APILLON_API_URL = CONFIG.VITE_APILLON_API_URL
export const COLLECTION_BUCKET_UUID = CONFIG.VITE_COLLECTION_BUCKET_UUID
export const APILLON_API_KEY = CONFIG.VITE_APILLON_API_KEY
export const APILLON_API_SECRET = CONFIG.VITE_APILLON_API_SECRET
